---
- name: Install awesome package
  package:
    name:
      - awesome
      - gnome-session
  become: true

- name: Copy awesome gnome session
  copy:
    src: awesome.session
    dest: "/usr/share/gnome-session/sessions/awesome.session"
  become: true

- name: Copy awesome desktop entry
  copy:
    src: awesome.desktop
    dest: "/usr/share/applications/awesome.desktop"
  become: true

- name: Get the configuration for awesome from git repo
  git:
    repo: "{{ config_repo }}"
    dest: "/home/{{ ansible_user_id }}/.config/awesome"
