---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get installed packages
      package_facts:
        manager: "auto"

    - name: Check if awesome is installed
      assert:
        that: "'awesome' in ansible_facts.packages"
        that: "'gnome-session' in ansible_facts.packages"

    - name: Get gnome session configuration for awesome wm
      stat:
        path: "/usr/share/gnome-session/sessions/awesome.session"
      register: awesomeSession

    - name: Check if awesome session exists
      assert:
        that: awesomeSession.stat.exists

    - name: Get gnome desktop entry for awesome wm
      stat:
        path: "usr/share/applications/awesome.desktop"
      register: awesomeDesktop

    - name: Check if awesome desktop entry exists
      assert:
        that: awesomeDesktop.stat.exists
