---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get installed packages
      package_facts:
        manager: "auto"

    - name: Check if awesome is installed
      assert:
        that: "'awesome' in ansible_facts.packages"
